<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.17">
  <POU Name="LD2_Blinker" Id="{9c7e8532-14cf-4047-9deb-4a59487370ef}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LD2_Blinker
VAR_INPUT
	execute:BOOL;
	period: TIME := T#1S;
	duty: REAL := 0.5;
END_VAR
VAR_OUTPUT
	output:BOOL;
END_VAR
VAR
	delay: TON;
END_VAR]]></Declaration>
    <Implementation>
      <LADDER>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="LadderImplementationObject">
              <v n="ModelJson">"{
  "$type": "LadderDataModel",
  "Networks": [
    {
      "$type": "Network",
      "Id": "-nIzDLP0",
      "Sequence": {
        "$type": "Sequence",
        "Elements": [
          {
            "$type": "Contact",
            "Operand": {
              "$type": "Operand",
              "Expression": "execute"
            }
          },
          {
            "$type": "Block",
            "BlockType": "TIMEMUL",
            "Instance": {
              "$type": "Operand"
            },
            "CallType": 3,
            "Inputs": [
              {
                "$type": "Input",
                "Pin": {
                  "$type": "Pin",
                  "Name": "EN"
                },
                "Sequence": {
                  "$type": "Sequence"
                }
              },
              {
                "$type": "Input",
                "Pin": {
                  "$type": "Pin",
                  "Name": "TIME_IN"
                },
                "Sequence": {
                  "$type": "Sequence",
                  "Elements": [
                    {
                      "$type": "InVariable",
                      "Operand": {
                        "$type": "Operand",
                        "Expression": "period"
                      }
                    }
                  ]
                }
              },
              {
                "$type": "Input",
                "Pin": {
                  "$type": "Pin",
                  "Name": "VALUE"
                },
                "Sequence": {
                  "$type": "Sequence",
                  "Elements": [
                    {
                      "$type": "InVariable",
                      "Operand": {
                        "$type": "Operand",
                        "Expression": "output"
                      }
                    },
                    {
                      "$type": "Block",
                      "BlockType": "SEL",
                      "Instance": {
                        "$type": "Operand"
                      },
                      "Inputs": [
                        {
                          "$type": "Input",
                          "Pin": {
                            "$type": "Pin",
                            "Name": "G",
                            "Modifier": {
                              "$type": "Modifier",
                              "Negation": true
                            }
                          },
                          "Sequence": {
                            "$type": "Sequence"
                          }
                        },
                        {
                          "$type": "Input",
                          "Pin": {
                            "$type": "Pin",
                            "Name": "IN0"
                          },
                          "Sequence": {
                            "$type": "Sequence",
                            "Elements": [
                              {
                                "$type": "InVariable",
                                "Operand": {
                                  "$type": "Operand",
                                  "Expression": "duty"
                                }
                              }
                            ]
                          }
                        },
                        {
                          "$type": "Input",
                          "Pin": {
                            "$type": "Pin",
                            "Name": "IN1"
                          },
                          "Sequence": {
                            "$type": "Sequence",
                            "Elements": [
                              {
                                "$type": "InVariable",
                                "Operand": {
                                  "$type": "Operand",
                                  "Expression": "1"
                                }
                              },
                              {
                                "$type": "Block",
                                "BlockType": "-",
                                "Instance": {
                                  "$type": "Operand"
                                },
                                "Inputs": [
                                  {
                                    "$type": "Input",
                                    "Pin": {
                                      "$type": "Pin"
                                    },
                                    "Sequence": {
                                      "$type": "Sequence"
                                    }
                                  },
                                  {
                                    "$type": "Input",
                                    "Pin": {
                                      "$type": "Pin"
                                    },
                                    "Sequence": {
                                      "$type": "Sequence",
                                      "Elements": [
                                        {
                                          "$type": "InVariable",
                                          "Operand": {
                                            "$type": "Operand",
                                            "Expression": "duty"
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "Outputs": [
                                  {
                                    "$type": "Output",
                                    "Pin": {
                                      "$type": "Pin"
                                    }
                                  }
                                ]
                              }
                            ]
                          }
                        }
                      ],
                      "Outputs": [
                        {
                          "$type": "Output",
                          "Pin": {
                            "$type": "Pin"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ],
            "Outputs": [
              {
                "$type": "Output",
                "Pin": {
                  "$type": "Pin",
                  "Name": "ENO"
                }
              },
              {
                "$type": "Output",
                "Pin": {
                  "$type": "Pin",
                  "Name": "TIMEMUL"
                },
                "OutVariable": {
                  "$type": "OutVariable",
                  "Operand": {
                    "$type": "Operand",
                    "Expression": "delay.PT"
                  }
                }
              }
            ],
            "En": true,
            "Eno": true
          },
          {
            "$type": "Block",
            "BlockType": "TON",
            "Instance": {
              "$type": "Operand",
              "Expression": "delay"
            },
            "CallType": 2,
            "Inputs": [
              {
                "$type": "Input",
                "Pin": {
                  "$type": "Pin",
                  "Name": "EN"
                },
                "Sequence": {
                  "$type": "Sequence"
                }
              },
              {
                "$type": "Input",
                "Pin": {
                  "$type": "Pin",
                  "Name": "IN",
                  "Modifier": {
                    "$type": "Modifier",
                    "Negation": true
                  }
                },
                "Sequence": {
                  "$type": "Sequence",
                  "Elements": [
                    {
                      "$type": "InVariable",
                      "Operand": {
                        "$type": "Operand",
                        "Expression": "delay.Q"
                      }
                    }
                  ]
                }
              },
              {
                "$type": "Input",
                "Pin": {
                  "$type": "Pin",
                  "Name": "PT"
                },
                "Sequence": {
                  "$type": "Sequence",
                  "Elements": [
                    {
                      "$type": "InVariable",
                      "Operand": {
                        "$type": "Operand"
                      }
                    }
                  ]
                }
              }
            ],
            "Outputs": [
              {
                "$type": "Output",
                "Pin": {
                  "$type": "Pin",
                  "Name": "ENO"
                }
              },
              {
                "$type": "Output",
                "Pin": {
                  "$type": "Pin",
                  "Name": "Q"
                },
                "OutVariable": {
                  "$type": "OutVariable",
                  "Operand": {
                    "$type": "Operand"
                  }
                }
              },
              {
                "$type": "Output",
                "Pin": {
                  "$type": "Pin",
                  "Name": "ET"
                },
                "OutVariable": {
                  "$type": "OutVariable",
                  "Operand": {
                    "$type": "Operand"
                  }
                }
              }
            ],
            "En": true,
            "Eno": true
          }
        ]
      }
    },
    {
      "$type": "Network",
      "Id": "Gme25e7W",
      "Sequence": {
        "$type": "Sequence",
        "Elements": [
          {
            "$type": "ParallelClosed",
            "Branches": [
              {
                "$type": "Sequence",
                "Elements": [
                  {
                    "$type": "Contact",
                    "Operand": {
                      "$type": "Operand",
                      "Expression": "delay.Q"
                    }
                  },
                  {
                    "$type": "Contact",
                    "Operand": {
                      "$type": "Operand",
                      "Expression": "output",
                      "Modifier": {
                        "$type": "Modifier",
                        "Negation": true
                      }
                    }
                  }
                ]
              },
              {
                "$type": "Sequence",
                "Elements": [
                  {
                    "$type": "Contact",
                    "Operand": {
                      "$type": "Operand",
                      "Expression": "output"
                    }
                  },
                  {
                    "$type": "Contact",
                    "Operand": {
                      "$type": "Operand",
                      "Expression": "delay.Q",
                      "Modifier": {
                        "$type": "Modifier",
                        "Negation": true
                      }
                    }
                  }
                ]
              }
            ]
          },
          {
            "$type": "Contact",
            "Operand": {
              "$type": "Operand",
              "Expression": "execute"
            }
          },
          {
            "$type": "Coil",
            "Operand": {
              "$type": "Operand",
              "Expression": "output"
            }
          }
        ]
      }
    }
  ]
}"</v>
            </o>
          </Data>
          <TypeList>
            <Type n="LadderImplementationObject">{f0fda5b8-8c48-4377-bbd5-c49444e4d26e}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </LADDER>
    </Implementation>
  </POU>
</TcPlcObject>